import { BlockType, GoalType, LevelConfig } from './GameTypes';

const base4 = [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad];
const base5 = [...base4, BlockType.Badluck];

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    name: '清理烦躁',
    steps: 24,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base4,
    initialTools: { star: 1, hammer: 1 },
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 8 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '拖动相邻方块进行交换。三个及以上相同情绪连在一起，就会被清除。先清理 8 个烦躁吧。',
  },
  {
    level: 2,
    name: '清理焦虑',
    steps: 26,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base4,
    initialTools: { star: 1, hammer: 1 },
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 10 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '每一关都有不同目标。这一次，优先清理焦虑方块。',
  },
  {
    level: 3,
    name: '双目标练习',
    steps: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base4,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 8 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 8 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '这一关有两个目标。两个目标都完成，才能通关。',
  },
  {
    level: 4,
    name: '清理坏情绪',
    steps: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [{ type: GoalType.ClearAnyNegative, target: 32 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '坏运气方块出现了。清理坏情绪表示消除任意负面情绪都算进度。',
  },
  {
    level: 5,
    name: '连击入门',
    steps: 30,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearAnyNegative, target: 35 },
      { type: GoalType.Combo, comboLevel: 2, target: 1 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '一次交换后，如果方块下落又自动形成消除，就会触发连击。本关试着完成一次 2 连击。',
  },
  {
    level: 6,
    name: '星星道具',
    steps: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 12 },
      { type: GoalType.ClearAnyNegative, target: 30 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '星星可以清除棋盘上同一种情绪。点击星星，再选择一个情绪方块，就会清除所有同类方块。',
  },
  {
    level: 7,
    name: '黑雾出现',
    steps: 30,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearFog, target: 6 },
      { type: GoalType.ClearAnyNegative, target: 25 },
    ],
    obstacles: { fog: 6, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '黑雾会盖住格子。让黑雾上的方块参与消除，就能清除黑雾。',
  },
  {
    level: 8,
    name: '锤子道具',
    steps: 30,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [{ type: GoalType.ClearFog, target: 8 }],
    obstacles: { fog: 8, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '锤子可以清除一个指定方块。如果黑雾位置不好处理，可以用锤子敲掉黑雾上的方块。',
  },
  {
    level: 9,
    name: '情绪能量',
    steps: 32,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.EmotionRelease, target: 1 },
      { type: GoalType.ClearAnyNegative, target: 35 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '消除坏情绪可以积攒能量。能量满后会触发情绪释放，并奖励一个星星。连击越多，能量涨得越快。',
  },
  {
    level: 10,
    name: '小幸运回来了',
    steps: 34,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 12 },
      { type: GoalType.ClearFog, target: 10 },
      { type: GoalType.EmotionRelease, target: 1 },
    ],
    obstacles: { fog: 10, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '最后一关，综合使用消除、道具和情绪能量。清理倒霉，驱散黑雾，让小幸运回来吧。',
  },
  {
    level: 11,
    name: '烦躁清理',
    steps: 24,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 24 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '烦躁变多了，但只要稳定消除就能完成。',
  },
  {
    level: 12,
    name: '压力积累',
    steps: 24,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 26 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '压力一点点累积，优先寻找连续消除机会。',
  },
  {
    level: 13,
    name: '低落散去',
    steps: 25,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 28 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '低落情绪变多了，多制造连锁会更轻松。',
  },
  {
    level: 14,
    name: '焦虑与烦躁',
    steps: 26,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 18 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 18 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '不要只盯着一种情绪，两个目标都要推进。',
  },
  {
    level: 15,
    name: '压力上头',
    steps: 26,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 20 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 18 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '坏运气和压力会一起出现，优先处理数量较多的目标。',
  },
  {
    level: 16,
    name: '坏运气扩散',
    steps: 27,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 22 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 18 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '坏运气正在扩散，别让步数浪费在无目标方块上。',
  },
  {
    level: 17,
    name: '情绪混杂',
    steps: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 15 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 15 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 15 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '三种情绪同时出现，均衡推进比只盯一种更重要。',
  },
  {
    level: 18,
    name: '情绪过载',
    steps: 29,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 18 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 18 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 16 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '情绪已经过载，尽量制造一次消除多个目标的机会。',
  },
  {
    level: 19,
    name: '混乱清晨',
    steps: 30,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 26 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 24 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '清晨的坏情绪很多，集中处理目标方块。',
  },
  {
    level: 20,
    name: '清空坏心情',
    steps: 32,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: { star: 1, hammer: 1 },
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 22 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 22 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 20 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    tutorial: '这是一次完整的情绪大扫除，合理规划每一步。',
  },
];
