import { BlockType, GoalType, LevelConfig } from './GameTypes';

const base4 = [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad];
const base5 = [...base4, BlockType.Badluck];

const noTools = { star: 0, hammer: 0 };
const starOnly = { star: 1, hammer: 0 };
const starHammer = { star: 1, hammer: 1 };

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    chapter: 1,
    name: '清理烦躁',
    steps: 20,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base4,
    initialTools: noTools,
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 10 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '第一章：认识坏心情\n交换相邻方块，连成 3 个相同情绪就能消除。',
  },
  {
    level: 2,
    chapter: 1,
    name: '焦虑变少一点',
    steps: 21,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base4,
    initialTools: noTools,
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 12 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '每一关都有指定目标，优先消除目标情绪。',
  },
  {
    level: 3,
    chapter: 1,
    name: '压力也要清理',
    steps: 22,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base4,
    initialTools: noTools,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 10 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 10 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '有时需要同时清理两种情绪，别只盯着一种。',
  },
  {
    level: 4,
    chapter: 1,
    name: '低落散开',
    steps: 23,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base4,
    initialTools: noTools,
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 18 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '目标数量变多了，尽量寻找更长的连线。',
  },
  {
    level: 5,
    chapter: 1,
    name: '连击入门',
    steps: 24,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: noTools,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 16 },
      { type: GoalType.Combo, comboLevel: 2, target: 1 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '一次消除后，如果下落又形成消除，就会产生连击。',
  },
  {
    level: 6,
    chapter: 1,
    name: '星星帮帮忙',
    steps: 24,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 16 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 12 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '星星可以帮你清理更多坏情绪，遇到困难时可以使用。',
  },
  {
    level: 7,
    chapter: 1,
    name: '黑雾来了',
    steps: 25,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 18 },
      { type: GoalType.ClearFog, target: 4 },
    ],
    obstacles: { fog: 4, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '黑雾会挡住心情，清除黑雾所在格的方块可以驱散黑雾。',
  },
  {
    level: 8,
    chapter: 1,
    name: '锤开阴影',
    steps: 25,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 18 },
      { type: GoalType.ClearFog, target: 6 },
    ],
    obstacles: { fog: 6, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '锤子可以直接敲掉关键位置，适合处理黑雾。',
  },
  {
    level: 9,
    chapter: 1,
    name: '情绪释放',
    steps: 26,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 18 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 14 },
      { type: GoalType.EmotionRelease, target: 1 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '持续消除会积累情绪能量，能量满后可以释放一次。',
  },
  {
    level: 10,
    chapter: 1,
    name: '第一章大扫除',
    steps: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 16 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 16 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 14 },
      { type: GoalType.ClearFog, target: 6 },
      { type: GoalType.Combo, comboLevel: 2, target: 1 },
    ],
    obstacles: { fog: 6, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '把前面学到的技巧都用上，完成第一次情绪大扫除。',
  },
  {
    level: 11,
    chapter: 2,
    name: '烦躁回潮',
    steps: 25,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: noTools,
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 26 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '第二章：整理坏心情\n坏心情又回来了，这次目标数量更多。',
  },
  {
    level: 12,
    chapter: 2,
    name: '压力堆积',
    steps: 25,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: noTools,
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 30 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '目标更多了，尽量不要浪费步数。',
  },
  {
    level: 13,
    chapter: 2,
    name: '低落天气',
    steps: 26,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 26 },
      { type: GoalType.ClearFog, target: 5 },
    ],
    obstacles: { fog: 5, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '低落和黑雾一起出现，先打开被挡住的区域。',
  },
  {
    level: 14,
    chapter: 2,
    name: '焦虑与烦躁',
    steps: 27,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 20 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 20 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '同时推进两个目标，不要让其中一个落后太多。',
  },
  {
    level: 15,
    chapter: 2,
    name: '倒霉小雨',
    steps: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 22 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 18 },
      { type: GoalType.ClearFog, target: 6 },
    ],
    obstacles: { fog: 6, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '坏运气和低落同时出现，黑雾会让空间变紧。',
  },
  {
    level: 16,
    chapter: 2,
    name: '压住压力',
    steps: 29,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 24 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 18 },
      { type: GoalType.EmotionRelease, target: 1 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '积累能量并释放，可以帮你更快清理压力。',
  },
  {
    level: 17,
    chapter: 2,
    name: '情绪混杂',
    steps: 30,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 16 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 16 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 16 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '三种情绪都要清理，均衡推进更重要。',
  },
  {
    level: 18,
    chapter: 2,
    name: '阴云压境',
    steps: 31,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 18 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 18 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 16 },
      { type: GoalType.ClearFog, target: 8 },
    ],
    obstacles: { fog: 8, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '黑雾变多了，先清出空间再处理目标。',
  },
  {
    level: 19,
    chapter: 2,
    name: '混乱清晨',
    steps: 31,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 28 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 26 },
      { type: GoalType.ClearFog, target: 4 },
      { type: GoalType.Combo, comboLevel: 2, target: 1 },
    ],
    obstacles: { fog: 4, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '目标量很高，尽量制造连击来节省步数。',
  },
  {
    level: 20,
    chapter: 2,
    name: '清空坏心情',
    steps: 33,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 22 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 22 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 20 },
      { type: GoalType.ClearFog, target: 8 },
      { type: GoalType.Combo, comboLevel: 2, target: 1 },
    ],
    obstacles: { fog: 8, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: false,
    tutorial: '这是一次真正的大扫除，合理规划每一步。',
  },
  {
    level: 21,
    chapter: 3,
    name: '一点阳光',
    steps: 27,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 24 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '第三章：找回好心情\n连成 4 个相同方块会生成治愈阳光，交换阳光可以清除周围一圈。',
  },
  {
    level: 22,
    chapter: 3,
    name: '阳光散开',
    steps: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [{ type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 34 }],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '目标很多，但阳光可以一次清理一大片。',
  },
  {
    level: 23,
    chapter: 3,
    name: '焦虑消融',
    steps: 29,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 24 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 22 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '用阳光同时推进多个目标，会更轻松。',
  },
  {
    level: 24,
    chapter: 3,
    name: '云开一点',
    steps: 30,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 24 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 20 },
      { type: GoalType.ClearFog, target: 5 },
    ],
    obstacles: { fog: 5, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '阳光也可以帮助打开被黑雾遮住的局面。',
  },
  {
    level: 25,
    chapter: 3,
    name: '好心情回来了',
    steps: 31,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 20 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 20 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 20 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '三种情绪一起清理，制造阳光能更快完成目标。',
  },
  {
    level: 26,
    chapter: 3,
    name: '阳光连线',
    steps: 31,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 26 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 26 },
      { type: GoalType.ClearFog, target: 4 },
      { type: GoalType.Combo, comboLevel: 2, target: 1 },
    ],
    obstacles: { fog: 4, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '尽量制造 4 连，阳光会让局面变得更轻松。',
  },
  {
    level: 27,
    chapter: 3,
    name: '坏运气快走',
    steps: 32,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starOnly,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 46 },
      { type: GoalType.EmotionRelease, target: 1 },
    ],
    obstacles: { fog: 0, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '坏运气很多，但阳光和情绪释放都能帮你快速清理。',
  },
  {
    level: 28,
    chapter: 3,
    name: '情绪大扫除',
    steps: 34,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Sad, target: 24 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 24 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 24 },
      { type: GoalType.ClearFog, target: 6 },
      { type: GoalType.Combo, comboLevel: 2, target: 1 },
    ],
    obstacles: { fog: 6, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '这是一次完整的大扫除，阳光是最好的帮手。',
  },
  {
    level: 29,
    chapter: 3,
    name: '最后的阴云',
    steps: 35,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Anxiety, target: 26 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 26 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 24 },
      { type: GoalType.ClearFog, target: 8 },
      { type: GoalType.Combo, comboLevel: 2, target: 1 },
    ],
    obstacles: { fog: 8, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '阴云快散了，抓住每一次制造阳光的机会。',
  },
  {
    level: 30,
    chapter: 3,
    name: '今天也好起来了',
    steps: 36,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: base5,
    initialTools: starHammer,
    goals: [
      { type: GoalType.ClearEmotion, emotion: BlockType.Annoyed, target: 28 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Pressure, target: 28 },
      { type: GoalType.ClearEmotion, emotion: BlockType.Badluck, target: 26 },
      { type: GoalType.ClearFog, target: 8 },
      { type: GoalType.Combo, comboLevel: 2, target: 1 },
    ],
    obstacles: { fog: 8, chain: 0, cloud: 0 },
    energyRequired: 100,
    enableSunshine: true,
    tutorial: '把最后的坏情绪清理掉，今天也会慢慢好起来。',
  },
];
