import { BlockType, GoalType, LevelConfig, ObstacleType, SpecialType } from './GameTypes';

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    moves: 25,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad],
    goals: [{ type: GoalType.ClearBlock, block: BlockType.Annoyed, count: 10 }],
    obstacles: [],
    energyRequired: 100,
  },
  {
    level: 2,
    moves: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad],
    goals: [
      { type: GoalType.ClearBlock, block: BlockType.Anxiety, count: 15 },
      { type: GoalType.ClearBlock, block: BlockType.Pressure, count: 10 },
    ],
    obstacles: [],
    energyRequired: 110,
  },
  {
    level: 3,
    moves: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad],
    goals: [
      { type: GoalType.Combo, count: 3 },
      { type: GoalType.ClearNegative, count: 20 },
    ],
    obstacles: [],
    energyRequired: 110,
  },
  {
    level: 4,
    moves: 28,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad, BlockType.Angry],
    goals: [{ type: GoalType.UseSpecial, special: SpecialType.Row, count: 2 }],
    obstacles: [],
    energyRequired: 120,
  },
  {
    level: 5,
    moves: 30,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad, BlockType.Angry],
    goals: [{ type: GoalType.ClearFog, count: 8 }],
    obstacles: [{ type: ObstacleType.Fog, positions: [{ row: 2, col: 2 }, { row: 2, col: 3 }, { row: 2, col: 4 }, { row: 3, col: 2 }, { row: 4, col: 5 }, { row: 5, col: 3 }, { row: 5, col: 4 }, { row: 5, col: 5 }] }],
    energyRequired: 120,
  },
  {
    level: 6,
    moves: 30,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad, BlockType.Angry, BlockType.Badluck],
    goals: [{ type: GoalType.UnlockChain, count: 6 }],
    obstacles: [{ type: ObstacleType.Chain, positions: [{ row: 1, col: 1 }, { row: 1, col: 6 }, { row: 3, col: 3 }, { row: 4, col: 4 }, { row: 6, col: 1 }, { row: 6, col: 6 }] }],
    energyRequired: 125,
  },
  {
    level: 7,
    moves: 30,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad, BlockType.Angry, BlockType.Badluck],
    goals: [{ type: GoalType.EmotionRelease, count: 1 }],
    obstacles: [],
    energyRequired: 80,
  },
  {
    level: 8,
    moves: 32,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad, BlockType.Angry, BlockType.Badluck],
    goals: [{ type: GoalType.ClearCloud, count: 5 }],
    obstacles: [{ type: ObstacleType.Cloud, positions: [{ row: 2, col: 5 }, { row: 5, col: 2 }, { row: 5, col: 5 }] }],
    energyRequired: 130,
    cloudSpreadEvery: 4,
  },
  {
    level: 9,
    moves: 32,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad, BlockType.Angry, BlockType.Badluck],
    goals: [
      { type: GoalType.ClearBlock, block: BlockType.Anxiety, count: 20 },
      { type: GoalType.ClearFog, count: 10 },
      { type: GoalType.UseSpecial, special: SpecialType.Row, count: 2 },
    ],
    obstacles: [{ type: ObstacleType.Fog, positions: [{ row: 1, col: 2 }, { row: 1, col: 5 }, { row: 2, col: 3 }, { row: 2, col: 4 }, { row: 3, col: 1 }, { row: 4, col: 6 }, { row: 5, col: 3 }, { row: 5, col: 4 }, { row: 6, col: 2 }, { row: 6, col: 5 }] }],
    energyRequired: 135,
  },
  {
    level: 10,
    moves: 34,
    boardWidth: 8,
    boardHeight: 8,
    availableBlocks: [BlockType.Annoyed, BlockType.Anxiety, BlockType.Pressure, BlockType.Sad, BlockType.Angry, BlockType.Badluck],
    goals: [
      { type: GoalType.ClearBlock, block: BlockType.Badluck, count: 15 },
      { type: GoalType.EmotionRelease, count: 1 },
      { type: GoalType.Combo, count: 3 },
    ],
    obstacles: [],
    energyRequired: 120,
  },
];
